### PR TITLE
Bundler support: run eye commands within a project path

### PR DESCRIPTION
**Pull request by alemorozov**
Hi Alex,

Thank you for the work on this gem!

I've added support for capistrano-bundler in this PR and would like to merge it to the upstream.

When using with capistrano-bundler, the working directory should contain Gemfile. Otherwise, it would fail looking for Gemfile.

I would like to answer any questions regarding this PR. Looking forward to your review.

### CODE REVIEW

**Comment by alexsergeyev** [comment]
I use eye to manage multiple projects deployed in different locations. So, eye itself not bundled with project. If there are any way to support both cases bundled and not bundled eye I will merge this patch.

**Comment by alemorozov** [comment]
This PR only adds the requirement to run the eye command inside the project path. It doesn't add bundler's calls anywhere in the code, because this work is done by the capistrano-bundler gem.

So it will work perfectly even with unbundled eye.

**Comment by alexsergeyev** [comment]
Yes. Everything looks fine. Thanks for PR

**Comment by alemorozov** [comment]
Alex, thank you very much!

**Pull request merged**
