### PR TITLE
Configuration of eye work dir

### PR DESCRIPTION
**Pull request by c0va23**
Hi!

I added the ability to configure working directory eye.

Now the eye works in a folder `release_path`. I would like to run in your eye `current_path`. On this added ability to customize the working directory.

By default, leave the old value `release_path`.

Sorry for my English. I used Google Translate.

### CODE REVIEW

**Comment by alexsergeyev** [comment]
Looks good. Nice feature :+1: . I think to add that as eye_command to allow to specify command line + args for eye. It will allow to do any required changed on command line. Will try to merge/update that in couple days

**Comment by alemorozov** [comment]
👍  @alexsergeyev, is there any thought when it will be merged and released?

**Comment by c0va23** [comment]
This PR will be accepted?

**Comment by alexsergeyev** [comment]
Rbenv/RVM detected automatically thanks @wojw5  pull request #10.  I have tested eye also without rbenv  and  ruby installed on custom path, but it simply solved with PATH env variable. Could you explain cases when you need this change?

**Comment by c0va23** [comment]
My issue described into MR. It not related to rvm/rbenv.

We use unicorn as rack-server. Presently code loaded from release directory. After deploy new version and hot-reload, new code not loaded, because working directory not changed (working directory stay on old release directory). We want use current directory as working. That fix a loading of new code after hot-reload.

**Comment by c0va23** [comment]
I've updated the PR. Now there is no conflict.

**Comment by gafrom** [comment]
@alexsergeyev Hi!
Please advice on whether this MR is ever gonna be merged?

This feature would really make our life easier.
Our case is:

*Eye* is a parent process for all services (puma, unicorn, redis, etc.). Thus all services inherit `Eye`'s environmental varibales, including `PWD` one.
Every deploy creates a new release directory, but *Eye* preserves outdated `PWD` env variable. That causes all services to use **wrong path**.

Look forward to a quick reply!
Thanx.

**Pull request merged**
